server:
  port: 8081
spring:
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos 服务端地址
#      discovery:
#        clusterName: CQ # 集群名称 重庆
  datasource:
    #url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql:3306/cloud-user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 120125hzy.
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: userservice # user的服务名称
mybatis:
  type-aliases-package: com.hzy.user.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.hzy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
    testMsg: 本地配置
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka