spring:
  rabbitmq:
    host: 192.168.193.40
    port: 5672
    username: test
    password: test
    virtual-host: /test
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制


logging:
  level:
    # com.hzy.config: debug
    com.hzy: debug




    # mq 连接重试
#   connection-timeout: 1s # 设置MQ的连接超时时间
#    template:
#      retry:
#        enabled: true # 开启超时重试机制
#        initial-interval: 1000ms # 失败后的初始等待时间
#        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier



#        max-attempts: 3 # 最大重试次数