server:
  port: 8080
spring:
  cloud:
    nacos:
      #server-addr: localhost:8848 # nacos 服务端地址
      server-addr: 192.168.193.40:8849 # nacos 服务端地址
      discovery:
        clusterName: CQ # 集群名称 重庆
        # namespace: 796ae418-4d19-4469-b8e7-10899e2581cf # 命名空间，填ID
        ephemeral: true # 是否是临时实例
  datasource:
    url: jdbc:mysql://mysql:3306/cloud-order?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/cloud-order?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 120125hzy.
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice # user的服务名称
mybatis:
  type-aliases-package: com.hzy.order.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.hzy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

# 作用域 针对某个微服务
userservice:
  ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: userservice # 指定对userservice这个服务饥饿加载
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数